# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

filterNodes <- function(xx_from, xx_to, xx_miRNA, xx_logFC, xx_pval, xx_dir, rows, rootgene, rootlogFC, tol, minify, miRNAtol, lFC, pVAL) {
    .Call('_GeneNetworkBuilder_filterNodes', PACKAGE = 'GeneNetworkBuilder', xx_from, xx_to, xx_miRNA, xx_logFC, xx_pval, xx_dir, rows, rootgene, rootlogFC, tol, minify, miRNAtol, lFC, pVAL)
}

